# Generated by Django 5.0.3 on 2024-05-27 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Fotografer')),
                ('specialization', models.CharField(max_length=255, verbose_name='Spesialisasi')),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Studio')),
                ('address', models.TextField(verbose_name='Alamat')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Nomor Telepon')),
            ],
        ),
        migrations.CreateModel(
            name='Photoshoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tanggal')),
                ('duration', models.DurationField(verbose_name='Durasi')),
                ('location', models.CharField(max_length=255, verbose_name='Lokasi')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photography.photographer', verbose_name='Fotografer')),
            ],
        ),
        migrations.AddField(
            model_name='photographer',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photography.studio', verbose_name='Studio'),
        ),
    ]
